// File: packages/neuronest-cli/src/sync/dts-emitter.ts
//
// Deterministic `.d.ts` emitter for the Skill_Type_Bundle.
// Generates the body of `node_modules/@neuronest/skills/index.d.ts` from
// a sorted-by-id list of SkillTypeCacheEntry records. Output is byte-stable
// across runs against the same input (Req 1.5).
//
// Validates: Requirements 1.3, 1.4, 1.5.
//
// Hard invariants:
//   - Header is fixed text (no timestamps, no machine identifiers).
//   - Skills are emitted in `id`-ascending order; `*Input`/`*Output`
//     interfaces are emitted in the same order, after all `export
//     function` declarations.
//   - JSDoc on functions is derived from `metadata.description`;
//     `@deprecated <reason>` is emitted when `metadata.deprecated` is set.
//   - JSDoc on interface members is derived from `metadata.paramDocs`.
//   - PascalCase collisions emit a `malformed_metadata` warning and skip
//     ALL colliding skills.
//   - JSON-Schema → TypeScript walker is dependency-free and deterministic;
//     unknown / unsupported shapes degrade to `unknown`.
//   - Output ends with exactly one trailing LF byte.

import type { SkillTypeCacheEntry, SyncWarning } from './types.js';

/** Fixed file header — no timestamps or machine info (Req 1.5). */
const DTS_HEADER =
  '// THIS FILE IS GENERATED BY `neuronest sync` — DO NOT EDIT.\n' +
  '// schemaVersion: 1\n' +
  '\n';

/**
 * Emit the `index.d.ts` text and any warnings raised during emission.
 *
 * @param entries Cache entries to emit. The function does not assume the
 *   array is pre-sorted; it makes its own sorted copy by `id` ascending.
 * @returns Object with the generated `dts` text and a `warnings` array
 *   containing one `malformed_metadata` warning per skipped colliding skill.
 */
export function emitDts(
  entries: SkillTypeCacheEntry[],
): { dts: string; warnings: SyncWarning[] } {
  const warnings: SyncWarning[] = [];

  // 1. Stable sort by id ascending — locale-independent code-point compare.
  const sorted = [...entries].sort((a, b) =>
    a.id < b.id ? -1 : a.id > b.id ? 1 : 0,
  );

  // 2. Group by PascalCase form to detect collisions.
  const groups = new Map<string, SkillTypeCacheEntry[]>();
  for (const entry of sorted) {
    const pc = pascalCase(entry.id);
    const bucket = groups.get(pc);
    if (bucket) {
      bucket.push(entry);
    } else {
      groups.set(pc, [entry]);
    }
  }

  // 3. Filter out collisions; warn once per skipped entry.
  const accepted: { entry: SkillTypeCacheEntry; pascal: string }[] = [];
  for (const entry of sorted) {
    const pc = pascalCase(entry.id);
    const bucket = groups.get(pc)!;
    if (bucket.length > 1) {
      const colliders = bucket.map((e) => e.id).join(', ');
      warnings.push({
        kind: 'malformed_metadata',
        skillRelPath: entry.relPath,
        detail:
          `PascalCase identifier collision on "${pc}" ` +
          `(skills: ${colliders}); skill skipped`,
      });
      continue;
    }
    accepted.push({ entry, pascal: pc });
  }

  // 4. Build the module body.
  const body: string[] = [];
  body.push("declare module '@neuronest/skills' {");

  // 4a. Function declarations.
  const fnBlocks: string[] = [];
  for (const { entry, pascal } of accepted) {
    fnBlocks.push(renderFunctionBlock(entry, pascal));
  }
  if (fnBlocks.length > 0) {
    body.push(fnBlocks.join('\n\n'));
  }

  // 4b. Interface declarations (after a blank line if any function above).
  const ifaceBlocks: string[] = [];
  for (const { entry, pascal } of accepted) {
    ifaceBlocks.push(renderInterfaceBlock(entry, pascal, 'Input'));
    ifaceBlocks.push(renderInterfaceBlock(entry, pascal, 'Output'));
  }
  if (ifaceBlocks.length > 0) {
    if (fnBlocks.length > 0) body.push('');
    body.push(ifaceBlocks.join('\n\n'));
  }

  body.push('}');

  // 5. Compose with header and exactly one trailing LF.
  const dts = DTS_HEADER + body.join('\n') + '\n';

  return { dts, warnings };
}

// --------------------------------------------------------------------------
// Function rendering
// --------------------------------------------------------------------------

/**
 * Render one `export function` declaration with its JSDoc leader.
 * Returned string is two-space indented and ends WITHOUT a trailing newline.
 */
function renderFunctionBlock(
  entry: SkillTypeCacheEntry,
  pascal: string,
): string {
  const lines: string[] = [];
  const docLines = buildFunctionJsDoc(entry);
  for (const line of docLines) lines.push('  ' + line);
  lines.push(
    `  export function ${entry.id}(input: ${pascal}Input): ` +
      `Promise<${pascal}Output>;`,
  );
  return lines.join('\n');
}

/**
 * Build the JSDoc lines (without indentation) for a function.
 * Returns an empty array when neither description nor deprecation is present.
 */
function buildFunctionJsDoc(entry: SkillTypeCacheEntry): string[] {
  const description = entry.metadata.description?.trim();
  const deprecated = entry.metadata.deprecated?.trim();

  const inner: string[] = [];
  if (description) inner.push(description);
  if (deprecated) inner.push(`@deprecated ${deprecated}`);

  if (inner.length === 0) return [];

  // Single-line form when there's exactly one short line and no newlines.
  if (inner.length === 1) {
    const only = inner[0]!;
    if (!only.includes('\n')) {
      return [`/** ${only} */`];
    }
  }

  // Multi-line form.
  const out = ['/**'];
  for (const block of inner) {
    for (const ln of block.split('\n')) out.push(` * ${ln}`);
  }
  out.push(' */');
  return out;
}

// --------------------------------------------------------------------------
// Interface rendering
// --------------------------------------------------------------------------

/**
 * Render one `export interface` declaration. Returned string is two-space
 * indented and ends WITHOUT a trailing newline.
 */
function renderInterfaceBlock(
  entry: SkillTypeCacheEntry,
  pascal: string,
  kind: 'Input' | 'Output',
): string {
  const name = `${pascal}${kind}`;
  const schema = kind === 'Input' ? entry.metadata.inputSchema : entry.metadata.outputSchema;
  const paramDocs = kind === 'Input' ? entry.metadata.paramDocs : undefined;

  const inner = renderInterfaceBody(schema, paramDocs);

  if (inner.length === 0) {
    return `  export interface ${name} {}`;
  }

  const lines: string[] = [];
  lines.push(`  export interface ${name} {`);
  for (const ln of inner) lines.push('    ' + ln);
  lines.push('  }');
  return lines.join('\n');
}

/**
 * Render the body of an interface (without surrounding braces).
 * Lines are returned without leading indentation; the caller indents them.
 */
function renderInterfaceBody(
  schema: unknown,
  paramDocs: Record<string, string> | undefined,
): string[] {
  if (!isPlainObject(schema)) return [];
  if (schema['type'] !== 'object') return [];

  const properties = isPlainObject(schema['properties']) ? schema['properties'] : {};
  const requiredArr = Array.isArray(schema['required']) ? schema['required'] : [];
  const requiredSet = new Set<string>(
    requiredArr.filter((v): v is string => typeof v === 'string'),
  );

  // Stable: sort property names alphabetically (code-point order).
  const propNames = Object.keys(properties).sort();
  if (propNames.length === 0) return [];

  const lines: string[] = [];
  for (let i = 0; i < propNames.length; i++) {
    const propName = propNames[i]!;
    const doc = paramDocs?.[propName]?.trim();
    if (doc) {
      // Single-line JSDoc when no embedded newline; otherwise multi-line.
      if (!doc.includes('\n')) {
        lines.push(`/** ${doc} */`);
      } else {
        lines.push('/**');
        for (const ln of doc.split('\n')) lines.push(` * ${ln}`);
        lines.push(' */');
      }
    }
    const optional = requiredSet.has(propName) ? '' : '?';
    const propType = renderType(properties[propName], 0);
    const safeKey = isValidJsIdentifier(propName) ? propName : JSON.stringify(propName);
    lines.push(`${safeKey}${optional}: ${propType};`);
  }
  return lines;
}

// --------------------------------------------------------------------------
// JSON Schema → TypeScript walker
// --------------------------------------------------------------------------

/**
 * Translate a JSON Schema fragment into a TypeScript type string.
 *
 * Supported:
 *   - `type: 'string' | 'number' | 'integer' | 'boolean' | 'null'`
 *     (`integer` widens to `number`).
 *   - `type: 'array'` with `items`  → `Array<T>`.
 *   - `type: 'object'` with `properties` + `required` → inline object type.
 *
 * Unknown / missing / unsupported shapes degrade to `unknown`.
 *
 * `depth` is the current brace-nesting depth — used to indent inline
 * object types correctly. Top-level call passes 0.
 */
function renderType(schema: unknown, depth: number): string {
  if (!isPlainObject(schema)) return 'unknown';

  const t = schema['type'];
  if (typeof t !== 'string') return 'unknown';

  switch (t) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    case 'array': {
      const items = schema['items'];
      const inner = items === undefined ? 'unknown' : renderType(items, depth);
      return `Array<${inner}>`;
    }
    case 'object': {
      const properties = isPlainObject(schema['properties']) ? schema['properties'] : {};
      const requiredArr = Array.isArray(schema['required']) ? schema['required'] : [];
      const requiredSet = new Set<string>(
        requiredArr.filter((v): v is string => typeof v === 'string'),
      );
      const propNames = Object.keys(properties).sort();
      if (propNames.length === 0) return '{}';

      // Indentation strategy: when the inline-object type is concatenated
      // into a property line that the caller indents at 4 spaces (module +
      // interface), the closing brace must land at that same column. Each
      // additional `depth` of nesting adds 2 spaces.
      const propIndent = '    ' + '  '.repeat(depth + 1);
      const closeIndent = '    ' + '  '.repeat(depth);

      const parts: string[] = ['{'];
      for (const name of propNames) {
        const optional = requiredSet.has(name) ? '' : '?';
        const childType = renderType(properties[name], depth + 1);
        const safeKey = isValidJsIdentifier(name) ? name : JSON.stringify(name);
        parts.push(`${propIndent}${safeKey}${optional}: ${childType};`);
      }
      parts.push(`${closeIndent}}`);
      return parts.join('\n');
    }
    default:
      return 'unknown';
  }
}

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

/**
 * Convert a skill identifier to PascalCase. Splits on:
 *   - non-alphanumeric runs (e.g. `-`, `_`, ` `, `.`)
 *   - case boundaries (lowercase → uppercase)
 *
 * Examples:
 *   `askDocs`     → `AskDocs`
 *   `ask-docs`    → `AskDocs`
 *   `ask_docs`    → `AskDocs`
 *   `render-chart`→ `RenderChart`
 *   `foo-bar`     → `FooBar`
 *   `fooBar`      → `FooBar`   (collides with `foo-bar`)
 */
export function pascalCase(id: string): string {
  // Insert separator before uppercase letters preceded by lowercase / digit.
  const expanded = id.replace(/([a-z0-9])([A-Z])/g, '$1 $2');
  const words = expanded.split(/[^a-zA-Z0-9]+/).filter((w) => w.length > 0);
  return words
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

/** Check whether a string is a valid JS identifier (no quoting required). */
function isValidJsIdentifier(s: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s);
}

/** Type-guard: is `v` a plain object (record)? */
function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}
