/**
 * Chat module — Authoritative header, structured composer, context items,
 * @ mention picker, rich response services, code actions, artifacts,
 * pagination, and stale-target handling.
 *
 * Requirements: 15.3, 15.4, 15.10, 16.1–16.10, 17.1–17.8
 */

export { ChatHeaderService } from './chat-header-service';
export { StructuredComposerService } from './structured-composer-service';
export { ContextItemStore } from './context-item-store';
export { AtMentionPicker } from './at-mention-picker';
export {
  RichResponseRenderer,
  TypedArtifactService,
  CitationService,
  CodeActionService,
  ArtifactViewerService,
  LargeOutputHandler,
  StaleTargetHandler,
} from './rich-response';
export type {
  HeaderViewModel,
  HeaderField,
  HeaderRuntimeData,
  SourceAttribution,
  InputModality,
  ComposerInput,
  ComposerMode,
  ValidationResult,
  ValidationIssue,
  ComposerContext,
  ModalityDeclaration,
  HistoryEntry,
  ContextResolutionProgress,
} from './types';
export type {
  ContextItemKind,
  ContextProvenance,
  StalenessStatus,
  ContextItem,
  ContextItemControls,
  ContextUsageSummary,
} from './context-item-store';
export type {
  PickerCategory,
  PickerSuggestion,
  PickerState,
  PickerDataProvider,
} from './at-mention-picker';
export type {
  RichContentType,
  RichContentBlock,
  RichContentMetadata,
  RenderResult,
  CspPolicy,
  RemoteResourceConsent,
  CodeBlockOptions,
  InteractiveCard,
  CardAction,
  DiffPreview,
  DiffHunk,
  TableData,
  ArtifactType,
  TypedArtifact,
  ArtifactMetadata,
  EmitArtifactInput,
  Citation,
  CitationPosition,
  AttachCitationInput,
  CitedResponseSegment,
  CodeActionKind,
  CodeAction,
  CodeBlockContext,
  TargetResolution,
  CodeActionResult,
  CodeActionError,
  RecoveryOption,
  CodeActionDelegate,
  ArtifactVersion,
  ArtifactDiff,
  ArtifactDiffHunk,
  ArtifactOriginLink,
  ExportFormat,
  ExportResult,
  ArtifactViewerState,
  LargeOutputConfig,
  OutputDisplayMode,
  OutputChunk,
  LargeOutputState,
  RemoteResourceGate,
  StaleReason,
  StaleTargetResult,
  RecoveryAction,
  RecoveryResult,
  StaleTargetDelegate,
  TargetCheckInput,
} from './rich-response';

// Chat Experience Authority (FUT-PKG-07-EXPERIENCE/T-002): composer islands,
// content-addressed attachments, the message action contract, in-chat approval
// cards, typed recovery, fail-closed content sanitization, and suggestions with
// the exact auto-send/prefill policy — built on the canonical chat projection,
// approval, and recovery authorities.
export {
  CHAT_EXPERIENCE_OWNER,
  toErrorEnvelope,
  sanitizeMermaid,
  sanitizeMarkup,
  sanitizeLink,
  ATTACHMENT_STATES,
  buildAttachmentRef,
  emptyComposerIsland,
  COMPOSER_EVENT_TYPES,
  COMPOSER_ISLAND_PROJECTION_ID,
  COMPOSER_ISLAND_PROJECTION,
  reduceComposerEvent,
  advanceComposerIsland,
  readComposerIsland,
  MESSAGE_ACTIONS,
  isMutatingAction,
  computeActionPlacement,
  copyResponseMarkdown,
  copyCodeBlock,
  expandResponse,
  routeMessageAction,
  buildEditBranchIntent,
  buildRetryBranchIntent,
  buildChatApprovalCard,
  RECOVERY_ACTIONS,
  buildRecoverySurface,
  buildSuggestionCard,
  buildStarterCards,
  buildPostTaskSuggestions,
  decideSuggestionClick,
} from './chat-experience';
export type {
  ExperienceResult,
  ExperienceError,
  MermaidRender,
  AttachmentState,
  AttachmentScanVerdict,
  AttachmentRef,
  ComposerIsland,
  QueuedMessage,
  ComposerEventType,
  MessageAction,
  ActionPlacement,
  CopyOutcome,
  ClipboardPort,
  ExpandSurface,
  ActionRoutePort,
  BranchIntent,
  ChatApprovalCard,
  RecoveryAction as ExperienceRecoveryAction,
  ReconciliationStatus,
  PreservedSessionState,
  RecoverySurface,
  SuggestionClass,
  SuggestionCard,
  SuggestionDisposition,
} from './chat-experience';
