// ─── Obsidian Adapter ───────────────────────────────────────────
// Full ChannelAdapter implementation for Obsidian using the Obsidian
// Local REST API community plugin. Connects via HTTP to the local REST
// server to create notes, search vault content, read notes, and link
// notes. Inbound commands are received via polling the vault for changes.
//
// Requirements: REQ 1.1, REQ 1.2, REQ 1.3, REQ 1.4, REQ 1.5,
// REQ 4.2, REQ 7.3, REQ 7.4

import { z } from 'zod';
import { BaseChannelAdapter } from './base-adapter';
import type { AdapterContext } from '../types/adapter';
import type { OutgoingMessage, ConnectResult, SendResult } from '../types/messages';
import type { AdapterCapabilities } from '../types/capabilities';
import type { TileMetadata } from '../types/tile-metadata';

// ─── Config Schema (REQ 1.6) ────────────────────────────────────

/**
 * Zod schema for Obsidian adapter configuration.
 * Requires the local REST API URL and API key from the Obsidian plugin.
 */
export const ObsidianConfigSchema = z.object({
  /** Base URL for the Obsidian Local REST API (e.g. https://127.0.0.1:27124) */
  apiUrl: z.string().url().default('https://127.0.0.1:27124'),
  /** API key generated by the Obsidian Local REST API plugin */
  apiKey: z.string().min(1),
  /** Optional polling interval in ms for detecting vault changes (default: 5000) */
  pollInterval: z.number().int().min(1000).default(5000),
});

export type ObsidianConfig = z.infer<typeof ObsidianConfigSchema>;

// ─── Command Parsing ────────────────────────────────────────────

/**
 * Supported Obsidian commands parsed from inbound content.
 */
type ObsidianCommand =
  | { action: 'create'; path: string; content: string }
  | { action: 'read'; path: string }
  | { action: 'search'; query: string }
  | { action: 'link'; sourcePath: string; targetPath: string };

// ─── Obsidian Adapter ───────────────────────────────────────────

export class ObsidianAdapter extends BaseChannelAdapter {
  readonly channelId = 'obsidian';

  readonly capabilities: AdapterCapabilities = {
    direction: 'bidirectional',
    supportsTyping: false,
    supportsRichMedia: false,
    deliveryMode: 'polling',
    requiresListener: false,
    implementationStatus: 'available',
  };

  readonly tileMetadata: TileMetadata = {
    displayName: 'Obsidian',
    emoji: '📝',
    description: 'Local knowledge base via REST API',
    actionTags: ['create note', 'search vault', 'read note', 'link notes'],
    sortOrder: 1012,
  };

  readonly configSchema = ObsidianConfigSchema;

  private config: ObsidianConfig | null = null;
  private pollTimer: ReturnType<typeof setInterval> | null = null;

  async connect(config: unknown, context: AdapterContext): Promise<ConnectResult> {
    this.ctx = context;

    // Validate config
    const parsed = this.configSchema.safeParse(config);
    if (!parsed.success) {
      const msg =
        'Obsidian adapter requires an API key from the Local REST API plugin.\n\n' +
        'Setup steps:\n' +
        '1. Install the "Local REST API" community plugin in Obsidian\n' +
        '2. Enable the plugin and copy the API key from its settings\n' +
        '3. Connect with: apiUrl=https://127.0.0.1:27124 apiKey=<your-key>\n\n' +
        `Validation errors: ${parsed.error.message}`;
      return {
        success: false,
        message: msg,
        error: { code: 'CONFIG_INVALID', message: msg },
      };
    }

    this.config = parsed.data;

    // Verify connectivity by hitting the server status endpoint
    try {
      const response = await this.request('GET', '/');
      if (!response.ok) {
        if (response.status === 401 || response.status === 403) {
          return this.authFailed('Invalid API key for Obsidian Local REST API.');
        }
        const body = await response.text().catch(() => '');
        return {
          success: false,
          message: `Obsidian REST API returned status ${response.status}: ${body}`,
          error: { code: 'PROVIDER_ERROR', message: `HTTP ${response.status}` },
        };
      }
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : String(err);
      if (errMsg.includes('ECONNREFUSED') || errMsg.includes('fetch failed')) {
        return {
          success: false,
          message:
            'Cannot connect to Obsidian Local REST API. Ensure Obsidian is running ' +
            'and the Local REST API plugin is enabled.',
          error: { code: 'PROVIDER_ERROR', message: errMsg },
        };
      }
      return {
        success: false,
        message: `Failed to connect to Obsidian: ${errMsg}`,
        error: { code: 'PROVIDER_ERROR', message: errMsg },
      };
    }

    // Start polling for vault changes (simulated inbound)
    this.startPolling();

    this.connected = true;
    this.log('info', 'Connected to Obsidian vault', { apiUrl: this.config.apiUrl });

    return {
      success: true,
      message: `Connected to Obsidian vault at ${this.config.apiUrl}`,
    };
  }

  async disconnect(): Promise<void> {
    this.stopPolling();
    this.connected = false;
    this.config = null;
    this.ctx = null;
  }

  async send(message: OutgoingMessage): Promise<SendResult> {
    if (!this.connected || !this.config) {
      return { success: false, message: 'Obsidian adapter is not connected' };
    }

    // Parse the outbound message as a command
    const command = this.parseCommand(message.content);
    if (!command) {
      // If not a structured command, create a note with the content
      return this.createNote(
        `NeuroNest/${new Date().toISOString().slice(0, 10)}-response.md`,
        message.content,
      );
    }

    switch (command.action) {
      case 'create':
        return this.createNote(command.path, command.content);
      case 'read':
        return this.readNote(command.path);
      case 'search':
        return this.searchVault(command.query);
      case 'link':
        return this.linkNotes(command.sourcePath, command.targetPath);
      default:
        return { success: false, message: 'Unknown Obsidian command' };
    }
  }

  // ─── Private: REST API Helpers ──────────────────────────────────

  /**
   * Make an authenticated HTTP request to the Obsidian Local REST API.
   */
  private async request(
    method: string,
    path: string,
    body?: string | Record<string, unknown>,
    contentType?: string,
  ): Promise<Response> {
    if (!this.config) {
      throw new Error('Obsidian adapter not configured');
    }

    const url = `${this.config.apiUrl}${path}`;
    const headers: Record<string, string> = {
      Authorization: `Bearer ${this.config.apiKey}`,
    };

    if (contentType) {
      headers['Content-Type'] = contentType;
    } else if (body && typeof body === 'object') {
      headers['Content-Type'] = 'application/json';
    } else if (body && typeof body === 'string') {
      headers['Content-Type'] = 'text/markdown';
    }

    const fetchOptions: RequestInit = {
      method,
      headers,
    };

    if (body) {
      fetchOptions.body = typeof body === 'object' ? JSON.stringify(body) : body;
    }

    return fetch(url, fetchOptions);
  }

  // ─── Private: Command Operations (REQ 7.3, REQ 7.4) ────────────

  /**
   * Create a new note in the Obsidian vault.
   * Uses PUT /vault/{path} to create or overwrite a note.
   */
  private async createNote(notePath: string, content: string): Promise<SendResult> {
    try {
      const encodedPath = encodeURIComponent(notePath).replace(/%2F/g, '/');
      const response = await this.request('PUT', `/vault/${encodedPath}`, content, 'text/markdown');

      if (response.ok) {
        return { success: true, message: `Note created: ${notePath}` };
      }

      const errorBody = await response.text().catch(() => '');
      return {
        success: false,
        message: `Failed to create note "${notePath}": HTTP ${response.status} ${errorBody}`,
      };
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : String(err);
      return { success: false, message: `Create note failed: ${errMsg}` };
    }
  }

  /**
   * Read a note from the Obsidian vault.
   * Uses GET /vault/{path} to retrieve note content.
   */
  private async readNote(notePath: string): Promise<SendResult> {
    try {
      const encodedPath = encodeURIComponent(notePath).replace(/%2F/g, '/');
      const response = await this.request('GET', `/vault/${encodedPath}`);

      if (response.ok) {
        const content = await response.text();
        return { success: true, message: content };
      }

      if (response.status === 404) {
        return { success: false, message: `Note not found: ${notePath}` };
      }

      const errorBody = await response.text().catch(() => '');
      return {
        success: false,
        message: `Failed to read note "${notePath}": HTTP ${response.status} ${errorBody}`,
      };
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : String(err);
      return { success: false, message: `Read note failed: ${errMsg}` };
    }
  }

  /**
   * Search the Obsidian vault for notes matching a query.
   * Uses POST /search/simple/ with a text query body.
   */
  private async searchVault(query: string): Promise<SendResult> {
    try {
      const response = await this.request(
        'POST',
        '/search/simple/',
        query,
        'text/plain',
      );

      if (response.ok) {
        const results = await response.json() as Array<{ filename: string; score?: number }>;
        if (results.length === 0) {
          return { success: true, message: 'No matching notes found.' };
        }
        const summary = results
          .slice(0, 10)
          .map((r, i) => `${i + 1}. ${r.filename}`)
          .join('\n');
        return { success: true, message: `Search results:\n${summary}` };
      }

      const errorBody = await response.text().catch(() => '');
      return {
        success: false,
        message: `Search failed: HTTP ${response.status} ${errorBody}`,
      };
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : String(err);
      return { success: false, message: `Search failed: ${errMsg}` };
    }
  }

  /**
   * Link two notes by appending a wiki-link in the source note.
   * Reads the source note, appends a [[target]] link, and writes it back.
   */
  private async linkNotes(sourcePath: string, targetPath: string): Promise<SendResult> {
    try {
      // Read the source note
      const encodedSource = encodeURIComponent(sourcePath).replace(/%2F/g, '/');
      const readResponse = await this.request('GET', `/vault/${encodedSource}`);

      if (!readResponse.ok) {
        return {
          success: false,
          message: `Cannot read source note "${sourcePath}": HTTP ${readResponse.status}`,
        };
      }

      const existingContent = await readResponse.text();

      // Derive the link target (filename without extension for wiki-link)
      const targetName = targetPath.replace(/\.md$/, '').split('/').pop() ?? targetPath;
      const wikiLink = `[[${targetName}]]`;

      // Check if the link already exists
      if (existingContent.includes(wikiLink)) {
        return { success: true, message: `Link to ${targetName} already exists in ${sourcePath}` };
      }

      // Append the wiki-link
      const updatedContent = existingContent.trimEnd() + `\n\n${wikiLink}\n`;
      const writeResponse = await this.request(
        'PUT',
        `/vault/${encodedSource}`,
        updatedContent,
        'text/markdown',
      );

      if (writeResponse.ok) {
        return { success: true, message: `Linked ${sourcePath} → ${targetName}` };
      }

      return {
        success: false,
        message: `Failed to write link: HTTP ${writeResponse.status}`,
      };
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : String(err);
      return { success: false, message: `Link notes failed: ${errMsg}` };
    }
  }

  // ─── Private: Command Parsing ───────────────────────────────────

  /**
   * Parse a message content string into an ObsidianCommand.
   * Supports structured command formats:
   * - "create:<path>:<content>"
   * - "read:<path>"
   * - "search:<query>"
   * - "link:<source>:<target>"
   */
  private parseCommand(content: string): ObsidianCommand | null {
    const trimmed = content.trim();

    // Match "action:arg1:arg2..." format
    const colonIndex = trimmed.indexOf(':');
    if (colonIndex === -1) return null;

    const action = trimmed.slice(0, colonIndex).toLowerCase();
    const rest = trimmed.slice(colonIndex + 1);

    switch (action) {
      case 'create': {
        const pathEnd = rest.indexOf(':');
        if (pathEnd === -1) return null;
        const path = rest.slice(0, pathEnd).trim();
        const noteContent = rest.slice(pathEnd + 1).trim();
        if (!path || !noteContent) return null;
        return { action: 'create', path, content: noteContent };
      }
      case 'read': {
        const path = rest.trim();
        if (!path) return null;
        return { action: 'read', path };
      }
      case 'search': {
        const query = rest.trim();
        if (!query) return null;
        return { action: 'search', query };
      }
      case 'link': {
        const pathEnd = rest.indexOf(':');
        if (pathEnd === -1) return null;
        const sourcePath = rest.slice(0, pathEnd).trim();
        const targetPath = rest.slice(pathEnd + 1).trim();
        if (!sourcePath || !targetPath) return null;
        return { action: 'link', sourcePath, targetPath };
      }
      default:
        return null;
    }
  }

  // ─── Private: Polling for Vault Changes ─────────────────────────

  /**
   * Start polling for vault changes. When changes are detected,
   * emit an inbound message with the vault path and note reference.
   * This simulates inbound commands for the bidirectional flow.
   */
  private startPolling(): void {
    if (!this.config) return;

    this.pollTimer = setInterval(async () => {
      await this.pollVaultChanges();
    }, this.config.pollInterval);
  }

  private stopPolling(): void {
    if (this.pollTimer) {
      clearInterval(this.pollTimer);
      this.pollTimer = null;
    }
  }

  /**
   * Poll the vault for recently modified files and emit inbound messages
   * for detected changes. Uses the /vault/ endpoint to list files and
   * checks modification timestamps.
   */
  private async pollVaultChanges(): Promise<void> {
    if (!this.connected || !this.config) return;

    try {
      const response = await this.request('GET', '/vault/');
      if (!response.ok) return;

      const data = (await response.json()) as { files?: string[] };
      const files = data.files;
      if (!Array.isArray(files)) return;

      // The REST API doesn't provide modification times in the listing,
      // so we track changes through a "NeuroNest inbox" convention:
      // notes in a specific folder (e.g., "NeuroNest/inbox/") are treated
      // as inbound commands when detected.
      const inboxFiles = files.filter(
        (f) => f.startsWith('NeuroNest/inbox/') && f.endsWith('.md'),
      );

      for (const filePath of inboxFiles) {
        await this.processInboxFile(filePath);
      }
    } catch (err: unknown) {
      // Silently handle polling errors to avoid log spam
      const errMsg = err instanceof Error ? err.message : String(err);
      this.log('warn', 'Vault poll failed', { error: errMsg });
    }
  }

  /**
   * Process a file from the inbox folder: read its content, emit as
   * inbound, then move it out of the inbox (delete it).
   */
  private async processInboxFile(filePath: string): Promise<void> {
    try {
      const encodedPath = encodeURIComponent(filePath).replace(/%2F/g, '/');
      const readResp = await this.request('GET', `/vault/${encodedPath}`);
      if (!readResp.ok) return;

      const content = await readResp.text();
      if (!content.trim()) return;

      // Emit as inbound message with vault path context
      this.emitInbound(`obsidian:${filePath}`, content.trim(), 'text');

      // Remove from inbox after processing (DELETE endpoint)
      await this.request('DELETE', `/vault/${encodedPath}`);
    } catch {
      // Best-effort: if processing fails, leave the file for next poll
    }
  }
}
