/**
 * Project File Header Generator
 * Adds branded headers to generated project files.
 * Reads app name and description from branding.json.
 */

import * as path from 'node:path';
import * as os from 'node:os';
import { FileEventEmitter } from '../main/file-event-emitter';
import { APP_NAME, APP_DESCRIPTION, APP_URL } from '../branding';

/**
 * Get the branded header line used across all file types.
 * Reads from branding.json so renaming the app updates all headers.
 */
function brandedHeaderLine(): string {
  return `Generated by ${APP_NAME} - ${APP_DESCRIPTION}`;
}

function brandedUrl(): string {
  return APP_URL;
}

// Header templates for different file types
const HEADERS: Record<string, string> = {
  // JavaScript/TypeScript family
  js: `/**
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

`,
  
  ts: `/**
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

`,

  // Java family (Java, Kotlin, Scala)
  java: `/**
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

`,

  // C/C++ family
  c: `/*
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

`,

  // Go
  go: `/*
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

`,

  // Rust
  rust: `/*
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

`,

  // Python
  py: `"""
Generated by NeuroNest - The AI Coding SuperAgent
https://github.com/NETGVai/NeuroNest

This file was automatically generated and may be overwritten.
Manual modifications should be made with caution.
"""

`,

  // Ruby
  rb: `#
# Generated by NeuroNest - The AI Coding SuperAgent
# https://github.com/NETGVai/NeuroNest
# 
# This file was automatically generated and may be overwritten.
# Manual modifications should be made with caution.
#

`,

  // PHP
  php: `<?php
/*
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

`,

  // Swift
  swift: `/*
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

`,

  // Dart
  dart: `/*
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

`,

  // C#
  cs: `/*
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

`,

  // CSS family
  css: `/*
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

`,

  // HTML/XML family
  html: `<!--
  Generated by NeuroNest - The AI Coding SuperAgent
  https://github.com/NETGVai/NeuroNest
  
  This file was automatically generated and may be overwritten.
  Manual modifications should be made with caution.
-->

`,

  // SQL
  sql: `--
-- Generated by NeuroNest - The AI Coding SuperAgent
-- https://github.com/NETGVai/NeuroNest
-- 
-- This file was automatically generated and may be overwritten.
-- Manual modifications should be made with caution.
--

`,

  // Shell scripts
  sh: `#!/bin/bash
#
# Generated by NeuroNest - The AI Coding SuperAgent
# https://github.com/NETGVai/NeuroNest
# 
# This file was automatically generated and may be overwritten.
# Manual modifications should be made with caution.
#

`,

  // PowerShell
  ps1: `#
# Generated by NeuroNest - The AI Coding SuperAgent
# https://github.com/NETGVai/NeuroNest
# 
# This file was automatically generated and may be overwritten.
# Manual modifications should be made with caution.
#

`,

  // Markdown
  md: `<!--
Generated by NeuroNest - The AI Coding SuperAgent
https://github.com/NETGVai/NeuroNest

This file was automatically generated and may be overwritten.
Manual modifications should be made with caution.
-->

`,

  // YAML/Config files
  yml: `#
# Generated by NeuroNest - The AI Coding SuperAgent
# https://github.com/NETGVai/NeuroNest
# 
# This file was automatically generated and may be overwritten.
# Manual modifications should be made with caution.
#

`,

  yaml: `#
# Generated by NeuroNest - The AI Coding SuperAgent
# https://github.com/NETGVai/NeuroNest
# 
# This file was automatically generated and may be overwritten.
# Manual modifications should be made with caution.
#

`,

  // Configuration files
  toml: `#
# Generated by NeuroNest - The AI Coding SuperAgent
# https://github.com/NETGVai/NeuroNest
# 
# This file was automatically generated and may be overwritten.
# Manual modifications should be made with caution.
#

`,

  // Dockerfile
  dockerfile: `#
# Generated by NeuroNest - The AI Coding SuperAgent
# https://github.com/NETGVai/NeuroNest
# 
# This file was automatically generated and may be overwritten.
# Manual modifications should be made with caution.
#

`,

  // R
  r: `#
# Generated by NeuroNest - The AI Coding SuperAgent
# https://github.com/NETGVai/NeuroNest
# 
# This file was automatically generated and may be overwritten.
# Manual modifications should be made with caution.
#

`,

  // MATLAB
  m: `%
% Generated by NeuroNest - The AI Coding SuperAgent
% https://github.com/NETGVai/NeuroNest
% 
% This file was automatically generated and may be overwritten.
% Manual modifications should be made with caution.
%

`,

  // Lua
  lua: `--
-- Generated by NeuroNest - The AI Coding SuperAgent
-- https://github.com/NETGVai/NeuroNest
-- 
-- This file was automatically generated and may be overwritten.
-- Manual modifications should be made with caution.
--

`,

  // Perl
  pl: `#
# Generated by NeuroNest - The AI Coding SuperAgent
# https://github.com/NETGVai/NeuroNest
# 
# This file was automatically generated and may be overwritten.
# Manual modifications should be made with caution.
#

`,

  // Haskell
  hs: `--
-- Generated by NeuroNest - The AI Coding SuperAgent
-- https://github.com/NETGVai/NeuroNest
-- 
-- This file was automatically generated and may be overwritten.
-- Manual modifications should be made with caution.
--

`,

  // Elixir
  ex: `#
# Generated by NeuroNest - The AI Coding SuperAgent
# https://github.com/NETGVai/NeuroNest
# 
# This file was automatically generated and may be overwritten.
# Manual modifications should be made with caution.
#

`,

  // Clojure
  clj: `;;
;; Generated by NeuroNest - The AI Coding SuperAgent
;; https://github.com/NETGVai/NeuroNest
;; 
;; This file was automatically generated and may be overwritten.
;; Manual modifications should be made with caution.
;;

`,

  // F#
  fs: `(*
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 *)

`,

  // Erlang
  erl: `%
% Generated by NeuroNest - The AI Coding SuperAgent
% https://github.com/NETGVai/NeuroNest
% 
% This file was automatically generated and may be overwritten.
% Manual modifications should be made with caution.
%

`,

  // Assembly
  asm: `;
; Generated by NeuroNest - The AI Coding SuperAgent
; https://github.com/NETGVai/NeuroNest
; 
; This file was automatically generated and may be overwritten.
; Manual modifications should be made with caution.
;

`,

  // LaTeX
  tex: `%
% Generated by NeuroNest - The AI Coding SuperAgent
% https://github.com/NETGVai/NeuroNest
% 
% This file was automatically generated and may be overwritten.
% Manual modifications should be made with caution.
%

`,

  // Vim script
  vim: `"
" Generated by NeuroNest - The AI Coding SuperAgent
" https://github.com/NETGVai/NeuroNest
" 
" This file was automatically generated and may be overwritten.
" Manual modifications should be made with caution.
"

`,

  // Makefile
  makefile: `#
# Generated by NeuroNest - The AI Coding SuperAgent
# https://github.com/NETGVai/NeuroNest
# 
# This file was automatically generated and may be overwritten.
# Manual modifications should be made with caution.
#

`
};

// File extensions to header type mapping
const EXTENSION_MAP: Record<string, string> = {
  // JavaScript/TypeScript family
  '.js': 'js',
  '.mjs': 'js',
  '.cjs': 'js',
  '.jsx': 'js',
  '.ts': 'ts',
  '.tsx': 'ts',
  
  // Java family
  '.java': 'java',
  '.kt': 'java',      // Kotlin
  '.kts': 'java',     // Kotlin script
  '.scala': 'java',   // Scala
  '.groovy': 'java',  // Groovy
  
  // C/C++ family
  '.c': 'c',
  '.cpp': 'c',
  '.cxx': 'c',
  '.cc': 'c',
  '.h': 'c',
  '.hpp': 'c',
  '.hxx': 'c',
  '.hh': 'c',
  
  // Go
  '.go': 'go',
  
  // Rust
  '.rs': 'rust',
  
  // Python
  '.py': 'py',
  '.pyx': 'py',       // Cython
  '.pyi': 'py',       // Python stub files
  '.pyw': 'py',       // Python Windows
  
  // Ruby
  '.rb': 'rb',
  '.rbw': 'rb',
  '.rake': 'rb',
  '.gemspec': 'rb',
  
  // PHP
  '.php': 'php',
  '.php3': 'php',
  '.php4': 'php',
  '.php5': 'php',
  '.phtml': 'php',
  
  // Swift
  '.swift': 'swift',
  
  // Dart
  '.dart': 'dart',
  
  // C#
  '.cs': 'cs',
  '.csx': 'cs',       // C# script
  
  // CSS family
  '.css': 'css',
  '.scss': 'css',
  '.sass': 'css',
  '.less': 'css',
  '.styl': 'css',     // Stylus
  
  // HTML/XML family
  '.html': 'html',
  '.htm': 'html',
  '.xhtml': 'html',
  '.xml': 'html',
  '.svg': 'html',
  '.vue': 'html',     // Vue.js
  '.svelte': 'html',  // Svelte
  
  // SQL
  '.sql': 'sql',
  '.mysql': 'sql',
  '.pgsql': 'sql',
  '.plsql': 'sql',
  
  // Shell scripts
  '.sh': 'sh',
  '.bash': 'sh',
  '.zsh': 'sh',
  '.fish': 'sh',
  '.ksh': 'sh',
  
  // PowerShell
  '.ps1': 'ps1',
  '.psm1': 'ps1',
  '.psd1': 'ps1',
  
  // Markdown
  '.md': 'md',
  '.markdown': 'md',
  '.mdown': 'md',
  '.mkd': 'md',
  '.mdx': 'md',       // MDX
  
  // YAML/Config files
  '.yml': 'yml',
  '.yaml': 'yaml',
  '.toml': 'toml',
  '.ini': 'yml',      // Use YAML-style comments for INI
  '.cfg': 'yml',      // Use YAML-style comments for config
  '.conf': 'yml',     // Use YAML-style comments for conf
  '.properties': 'yml', // Java properties
  
  // Docker
  '.dockerfile': 'dockerfile',
  
  // R
  '.r': 'r',
  '.R': 'r',
  
  // MATLAB
  '.m': 'm',
  
  // Lua
  '.lua': 'lua',
  
  // Perl
  '.pl': 'pl',
  '.pm': 'pl',
  '.perl': 'pl',
  
  // Haskell
  '.hs': 'hs',
  '.lhs': 'hs',
  
  // Elixir
  '.ex': 'ex',
  '.exs': 'ex',
  
  // Clojure
  '.clj': 'clj',
  '.cljs': 'clj',
  '.cljc': 'clj',
  '.edn': 'clj',
  
  // F#
  '.fs': 'fs',
  '.fsx': 'fs',
  '.fsi': 'fs',
  
  // Erlang
  '.erl': 'erl',
  '.hrl': 'erl',
  
  // Assembly
  '.asm': 'asm',
  '.s': 'asm',
  '.S': 'asm',
  
  // LaTeX
  '.tex': 'tex',
  '.latex': 'tex',
  '.sty': 'tex',
  '.cls': 'tex',
  
  // Vim script
  '.vim': 'vim',
  '.vimrc': 'vim',
  
  // Other languages
  '.jl': 'rb',        // Julia (use Ruby-style comments)
  '.nim': 'rb',       // Nim (use Ruby-style comments)
  '.cr': 'rb',        // Crystal (use Ruby-style comments)
  '.zig': 'c',        // Zig (use C-style comments)
  '.v': 'c',          // V (use C-style comments)
  '.d': 'c',          // D (use C-style comments)
  '.pas': 'c',        // Pascal (use C-style comments)
  '.pp': 'c',         // Pascal (use C-style comments)
  '.ada': 'sql',      // Ada (use SQL-style comments)
  '.adb': 'sql',      // Ada body
  '.ads': 'sql',      // Ada spec
  '.f': 'c',          // Fortran (use C-style comments)
  '.f90': 'c',        // Fortran 90
  '.f95': 'c',        // Fortran 95
  '.for': 'c',        // Fortran
  '.cob': 'c',        // COBOL (use C-style comments)
  '.cbl': 'c',        // COBOL
  '.lisp': 'clj',     // Lisp (use Clojure-style comments)
  '.lsp': 'clj',      // Lisp
  '.scm': 'clj',      // Scheme
  '.rkt': 'clj',      // Racket
  '.ml': 'c',         // OCaml (use C-style comments)
  '.mli': 'c',        // OCaml interface
  '.elm': 'sql',      // Elm (use SQL-style comments)
  '.purs': 'sql',     // PureScript (use SQL-style comments)
  '.reason': 'c',     // ReasonML (use C-style comments)
  '.re': 'c',         // ReasonML
  '.rei': 'c',        // ReasonML interface
  '.tcl': 'rb',       // Tcl (use Ruby-style comments)
  '.tk': 'rb',        // Tk
  '.vb': 'c',         // Visual Basic (use C-style comments)
  '.vbs': 'c',        // VBScript
  '.bas': 'c',        // BASIC
  '.awk': 'rb',       // AWK (use Ruby-style comments)
  '.sed': 'rb',       // sed (use Ruby-style comments)
  '.proto': 'c',      // Protocol Buffers (use C-style comments)
  '.thrift': 'c',     // Apache Thrift (use C-style comments)
  '.graphql': 'rb',   // GraphQL (use Ruby-style comments)
  '.gql': 'rb',       // GraphQL
  '.tf': 'rb',        // Terraform (use Ruby-style comments)
  '.hcl': 'rb',       // HashiCorp Configuration Language
  '.nomad': 'rb',     // Nomad (use Ruby-style comments)
  '.consul': 'rb',    // Consul (use Ruby-style comments)
  '.vault': 'rb',     // Vault (use Ruby-style comments)
  '.pkr.hcl': 'rb',   // Packer (use Ruby-style comments)
  '.jsonnet': 'c',    // Jsonnet (use C-style comments)
  '.libsonnet': 'c',  // Jsonnet library
  '.dhall': 'sql',    // Dhall (use SQL-style comments)
  '.nix': 'rb',       // Nix (use Ruby-style comments)
  '.bzl': 'rb',       // Bazel (use Ruby-style comments)
  '.BUILD': 'rb',     // Bazel BUILD files
  '.WORKSPACE': 'rb', // Bazel WORKSPACE files
  '.cmake': 'rb',     // CMake (use Ruby-style comments)
  '.gradle': 'c',     // Gradle (use C-style comments)
  '.sbt': 'c',        // SBT (use C-style comments)
  '.maven': 'html',   // Maven (use XML-style comments)
  '.pom': 'html',     // Maven POM
  '.ant': 'html',     // Apache Ant (use XML-style comments)
  '.build': 'html'    // MSBuild (use XML-style comments)
};

// File extensions to skip (files that don't support comments)
const SKIP_EXTENSIONS = [
  '.json'  // JSON doesn't support comments
];

/**
 * Check if a file already has a branded header
 */
function hasNeuroNestHeader(content: string): boolean {
  return content.includes('Generated by ' + APP_NAME) || 
         content.includes(APP_NAME + ' - ' + APP_DESCRIPTION) ||
         // Legacy check for files generated before branding was externalized
         content.includes('Generated by NeuroNest') || 
         content.includes('NeuroNest - The AI Coding SuperAgent');
}

/**
 * Add header to file content based on file type
 */
export function addHeaderToContent(content: string, filePath: string): string {
  const path = require('node:path');
  const extension = path.extname(filePath).toLowerCase();
  const fileName = path.basename(filePath);
  
  // Skip files that don't support comments
  if (SKIP_EXTENSIONS.includes(extension)) {
    return content;
  }
  
  // Skip if already has header
  if (hasNeuroNestHeader(content)) {
    return content;
  }
  
  let headerType = EXTENSION_MAP[extension];
  
  // Special handling for files without extensions
  if (!headerType && fileName) {
    const lowerFileName = fileName.toLowerCase();
    if (lowerFileName === 'dockerfile' || lowerFileName.startsWith('dockerfile.')) {
      headerType = 'dockerfile';
    } else if (lowerFileName === 'makefile' || lowerFileName === 'gnumakefile') {
      headerType = 'makefile';
    } else if (lowerFileName === 'rakefile') {
      headerType = 'rb';
    } else if (lowerFileName === 'gemfile') {
      headerType = 'rb';
    } else if (lowerFileName === 'vagrantfile') {
      headerType = 'rb';
    } else if (lowerFileName === 'fastfile' || lowerFileName === 'appfile' || lowerFileName === 'deliverfile') {
      headerType = 'rb'; // Fastlane files
    }
  }
  
  if (!headerType || !HEADERS[headerType]) {
    return content;
  }

  const header = HEADERS[headerType];

  // Special handling for PHP files (preserve opening tag)
  if (headerType === 'php') {
    if (content.startsWith('<?php')) {
      const lines = content.split('\n');
      const phpTag = lines[0];
      const restContent = lines.slice(1).join('\n');
      return phpTag + '\n' + header + restContent;
    }
  }

  // Special handling for shell scripts (preserve shebang)
  if (headerType === 'sh') {
    if (content.startsWith('#!')) {
      const lines = content.split('\n');
      const shebang = lines[0];
      const restContent = lines.slice(1).join('\n');
      return shebang + '\n' + header.replace('#!/bin/bash\n', '') + restContent;
    }
  }

  return header + content;
}

/**
 * Add header to a file and write it
 */
export function writeFileWithHeader(filePath: string, content: string): void {
  const fs = require('node:fs');
  
  // Add header to content
  const contentWithHeader = addHeaderToContent(content, filePath);
  
  try {
    // Ensure directory exists
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    
    // Write file
    fs.writeFileSync(filePath, contentWithHeader, 'utf-8');
  } catch (writeErr: any) {
    // Handle EPERM, EACCES, and other write errors gracefully
    if (writeErr.code === 'EPERM' || writeErr.code === 'EACCES' || writeErr.code === 'EROFS') {
      console.warn('[writeFileWithHeader] Permission denied writing to:', filePath, '—', writeErr.code);
      return; // Skip this file silently
    }
    if (writeErr.code === 'ENAMETOOLONG' || writeErr.code === 'EINVAL') {
      console.warn('[writeFileWithHeader] Invalid path:', filePath, '—', writeErr.code);
      return;
    }
    throw writeErr; // Re-throw unexpected errors
  }
  
  // Emit file creation event for real-time file tree updates
  try {
    // Extract projectId and relative path from the full file path
    const neuronestProjectsPath = path.join(os.homedir(), '.neuronest', 'projects');
    const normalizedFilePath = path.resolve(filePath);
    const normalizedProjectsPath = path.resolve(neuronestProjectsPath);
    
    // Check if this file is within a NeuroNest project directory
    if (normalizedFilePath.startsWith(normalizedProjectsPath + path.sep)) {
      const relativePath = path.relative(normalizedProjectsPath, normalizedFilePath);
      const pathParts = relativePath.split(path.sep);
      
      if (pathParts.length >= 2) {
        const projectId = pathParts[0];
        const relativeFilePath = pathParts.slice(1).join(path.sep);
        
        // Use FileEventEmitter to emit the file creation event
        const emitter = FileEventEmitter.getInstance();
        emitter.emitFileCreated(projectId, relativeFilePath);
      }
    }
  } catch (error) {
    // Log error but don't fail the file write operation
    console.error('[writeFileWithHeader] Error emitting file creation event:', error);
  }
}