/**
 * IPC Registry — Typed IPC Router with Zod Validation
 *
 * Replaces the monolithic ipcMain.handle pattern with a structured registry
 * that validates all incoming messages against Zod schemas before dispatching
 * to handlers. Returns structured error responses on validation failure.
 *
 * Usage:
 *   const registry = new IPCRegistry();
 *   registry.register({
 *     channel: 'chat:send',
 *     requestSchema: z.object({ message: z.string() }),
 *     responseSchema: z.object({ id: z.string() }),
 *     handler: async (_event, req) => ({ id: generateId() }),
 *   });
 *   registry.attachAll(); // wires to ipcMain.handle
 */

import { ipcMain } from 'electron';
import type { IpcMainInvokeEvent } from 'electron';
import type { IPCHandlerDef, IPCResponse, IPCValidationError, ValidationResult } from './types.js';

// ─── IPCRegistry ────────────────────────────────────────────────

export class IPCRegistry {
  private handlers: Map<string, IPCHandlerDef<unknown, unknown>> = new Map();

  /**
   * Register an IPC handler with Zod schema validation.
   *
   * Enforces that both request and response schemas are defined.
   * Throws if the channel is already registered or schemas are missing.
   */
  register<Req, Res>(def: IPCHandlerDef<Req, Res>): void {
    if (!def.channel || typeof def.channel !== 'string') {
      throw new Error('IPCRegistry: channel must be a non-empty string');
    }

    if (!def.requestSchema) {
      throw new Error(`IPCRegistry: requestSchema is required for channel "${def.channel}"`);
    }

    if (!def.responseSchema) {
      throw new Error(`IPCRegistry: responseSchema is required for channel "${def.channel}"`);
    }

    if (!def.handler || typeof def.handler !== 'function') {
      throw new Error(`IPCRegistry: handler must be a function for channel "${def.channel}"`);
    }

    if (this.handlers.has(def.channel)) {
      throw new Error(`IPCRegistry: channel "${def.channel}" is already registered`);
    }

    this.handlers.set(def.channel, def as IPCHandlerDef<unknown, unknown>);
  }

  /**
   * Attach all registered handlers to ipcMain.handle.
   * Each handler is wrapped with Zod validation on the request payload.
   */
  attachAll(): void {
    for (const [channel, def] of this.handlers) {
      ipcMain.handle(channel, async (event: IpcMainInvokeEvent, ...args: unknown[]) => {
        return this.dispatch(def, event, args[0]);
      });
    }
  }

  /**
   * Dispatch a single IPC invocation with validation.
   * Exported for direct testing without wiring to ipcMain.
   */
  async dispatch(
    def: IPCHandlerDef<unknown, unknown>,
    event: IpcMainInvokeEvent,
    rawPayload: unknown
  ): Promise<IPCResponse<unknown>> {
    // Validate request payload against the Zod schema
    const parseResult = def.requestSchema.safeParse(rawPayload);

    if (!parseResult.success) {
      const validationError = this.buildValidationError(def.channel, parseResult.error);
      return { success: false, error: validationError };
    }

    // Dispatch to the handler with validated data
    const result = await def.handler(event, parseResult.data);
    return { success: true, data: result };
  }

  /**
   * Validate all registered handler definitions.
   * Checks that schemas are properly defined and channels are well-formed.
   */
  validateAll(): ValidationResult[] {
    const results: ValidationResult[] = [];

    for (const [channel, def] of this.handlers) {
      const issues: string[] = [];

      if (!channel || channel.trim().length === 0) {
        issues.push('Channel name is empty');
      }

      if (!def.requestSchema) {
        issues.push('Missing requestSchema');
      }

      if (!def.responseSchema) {
        issues.push('Missing responseSchema');
      }

      if (!def.handler || typeof def.handler !== 'function') {
        issues.push('Handler is not a function');
      }

      results.push({
        channel,
        valid: issues.length === 0,
        issues,
      });
    }

    return results;
  }

  /**
   * Generate TypeScript declaration content (.d.ts) for the preload layer.
   * Auto-generates typed channel signatures from registered Zod schemas.
   *
   * The output declares a global `electronAPI` with invoke methods for each channel,
   * using Zod's inferred types for request and response.
   */
  generatePreloadTypes(): string {
    const lines: string[] = [
      '// Auto-generated by IPCRegistry.generatePreloadTypes()',
      '// Do not edit manually — regenerate when IPC handlers change.',
      '',
      'interface ElectronAPI {',
    ];

    for (const [channel, def] of this.handlers) {
      const reqType = this.zodSchemaToTypeString(def.requestSchema);
      const resType = this.zodSchemaToTypeString(def.responseSchema);
      const safeName = this.channelToMethodName(channel);
      lines.push(`  ${safeName}(req: ${reqType}): Promise<{ success: true; data: ${resType} } | { success: false; error: { channel: string; fieldPath: string; expected: string; received: string } }>;`);
    }

    lines.push('}');
    lines.push('');
    lines.push('declare global {');
    lines.push('  interface Window {');
    lines.push('    electronAPI: ElectronAPI;');
    lines.push('  }');
    lines.push('}');
    lines.push('');
    lines.push('export {};');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Returns the number of registered handlers.
   */
  get size(): number {
    return this.handlers.size;
  }

  /**
   * Check if a channel is registered.
   */
  has(channel: string): boolean {
    return this.handlers.has(channel);
  }

  /**
   * Get a registered handler definition (for testing purposes).
   */
  get(channel: string): IPCHandlerDef<unknown, unknown> | undefined {
    return this.handlers.get(channel);
  }

  // ─── Private Helpers ────────────────────────────────────────────

  /**
   * Build a structured validation error from a Zod error.
   */
  private buildValidationError(channel: string, zodError: { issues: Array<{ path: PropertyKey[]; message: string; code?: string; expected?: unknown; received?: unknown; input?: unknown }> }): IPCValidationError {
    // Use the first issue for the structured error
    const firstIssue = zodError.issues[0];

    if (!firstIssue) {
      return {
        channel,
        fieldPath: '',
        expected: 'valid input',
        received: 'invalid input',
      };
    }

    const fieldPath = firstIssue.path
      .map((segment) => (typeof segment === 'number' ? `[${segment}]` : String(segment)))
      .join('.')
      .replace(/\.\[/g, '[');

    const expected = firstIssue.expected !== undefined
      ? String(firstIssue.expected)
      : firstIssue.message;

    const received = firstIssue.input !== undefined
      ? String(typeof firstIssue.input)
      : firstIssue.received !== undefined
        ? String(firstIssue.received)
        : 'unknown';

    return {
      channel,
      fieldPath,
      expected,
      received,
    };
  }

  /**
   * Convert a channel name to a safe method name.
   * 'chat:send-message' → 'chatSendMessage'
   */
  private channelToMethodName(channel: string): string {
    return channel
      .split(/[:\-_.]/)
      .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
      .join('');
  }

  /**
   * Attempt to produce a reasonable TypeScript type string from a Zod schema.
   * Falls back to 'unknown' for complex schemas.
   */
  private zodSchemaToTypeString(schema: { _zod?: { def?: { type?: string; shape?: Record<string, unknown> } }; description?: string }): string {
    // Access Zod v4 internals for basic type extraction
    const def = (schema as any)?._zod?.def;
    if (!def) return 'unknown';

    switch (def.type) {
      case 'string':
        return 'string';
      case 'number':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'undefined':
        return 'undefined';
      case 'null':
        return 'null';
      case 'void':
        return 'void';
      case 'object': {
        if (def.shape) {
          const entries = Object.entries(def.shape as Record<string, unknown>);
          if (entries.length === 0) return 'Record<string, unknown>';
          const fields = entries.map(([key, val]) => {
            const valType = this.zodSchemaToTypeString(val as any);
            return `${key}: ${valType}`;
          });
          return `{ ${fields.join('; ')} }`;
        }
        return 'Record<string, unknown>';
      }
      case 'array': {
        const innerType = def.element ? this.zodSchemaToTypeString(def.element as any) : 'unknown';
        return `${innerType}[]`;
      }
      default:
        return 'unknown';
    }
  }
}
