/**
 * Generated by NeuroNest - The AI Coding SuperAgent
 * https://github.com/NETGVai/NeuroNest
 * 
 * This file was automatically generated and may be overwritten.
 * Manual modifications should be made with caution.
 */

import type Database from 'better-sqlite3';

export const version = 1;
export const description = 'Initial schema with all core tables';

export function up(db: Database.Database): void {
  db.exec(`
    -- Sessions
    CREATE TABLE sessions (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        project_dir TEXT,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Messages within sessions
    CREATE TABLE messages (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        role TEXT NOT NULL CHECK(role IN ('user', 'assistant', 'system', 'tool')),
        content TEXT NOT NULL,
        tool_calls TEXT,
        token_usage TEXT,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Agent templates
    CREATE TABLE agent_templates (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        role TEXT NOT NULL,
        system_prompt TEXT NOT NULL,
        domain TEXT,
        model_preference TEXT NOT NULL,
        tool_permissions TEXT NOT NULL,
        identity_files TEXT NOT NULL,
        is_builtin BOOLEAN NOT NULL DEFAULT FALSE,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Active agents per session
    CREATE TABLE session_agents (
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        agent_id TEXT NOT NULL,
        template_id TEXT NOT NULL REFERENCES agent_templates(id),
        model_config TEXT NOT NULL,
        PRIMARY KEY (session_id, agent_id)
    );

    -- Agent performance records
    CREATE TABLE performance_records (
        id TEXT PRIMARY KEY,
        agent_id TEXT NOT NULL,
        task_description TEXT NOT NULL,
        quality_score REAL,
        tokens_used INTEGER,
        duration_ms INTEGER,
        improvement_version INTEGER,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Self-improvement history
    CREATE TABLE improvement_records (
        id TEXT PRIMARY KEY,
        agent_id TEXT NOT NULL,
        version INTEGER NOT NULL,
        changes TEXT NOT NULL,
        performance_before REAL,
        performance_after REAL,
        applied BOOLEAN NOT NULL DEFAULT FALSE,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Execution history for dashboard
    CREATE TABLE execution_history (
        id TEXT PRIMARY KEY,
        type TEXT NOT NULL CHECK(type IN ('agent', 'swarm', 'orchestrator')),
        session_id TEXT REFERENCES sessions(id),
        agent_ids TEXT NOT NULL,
        task TEXT NOT NULL,
        status TEXT NOT NULL,
        tokens_used INTEGER,
        estimated_cost REAL,
        duration_ms INTEGER,
        orchestration_patterns TEXT,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Token usage tracking
    CREATE TABLE token_usage (
        id TEXT PRIMARY KEY,
        provider_id TEXT NOT NULL,
        model TEXT NOT NULL,
        prompt_tokens INTEGER NOT NULL,
        completion_tokens INTEGER NOT NULL,
        estimated_cost REAL NOT NULL,
        session_id TEXT REFERENCES sessions(id),
        agent_id TEXT,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Permission audit log
    CREATE TABLE permission_audit (
        id TEXT PRIMARY KEY,
        tool_id TEXT NOT NULL,
        agent_id TEXT NOT NULL,
        input TEXT NOT NULL,
        decision TEXT NOT NULL CHECK(decision IN ('approved', 'denied')),
        mode TEXT NOT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Plugin registry
    CREATE TABLE plugins (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        version TEXT NOT NULL,
        manifest TEXT NOT NULL,
        enabled BOOLEAN NOT NULL DEFAULT TRUE,
        installed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Application configuration
    CREATE TABLE config (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Budget alerts
    CREATE TABLE budget_alerts (
        id TEXT PRIMARY KEY,
        provider_id TEXT,
        threshold REAL NOT NULL,
        enabled BOOLEAN NOT NULL DEFAULT TRUE,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Prompt optimizer history
    CREATE TABLE prompt_history (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL REFERENCES sessions(id),
        agent_id TEXT NOT NULL,
        original TEXT NOT NULL,
        optimized TEXT NOT NULL,
        profile TEXT NOT NULL,
        techniques TEXT NOT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Flow schedules (CAO)
    CREATE TABLE flows (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        schedule TEXT NOT NULL,
        orchestrator_template TEXT NOT NULL,
        enabled BOOLEAN NOT NULL DEFAULT TRUE,
        last_run DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Indexes for common queries
    CREATE INDEX idx_messages_session_id ON messages(session_id);
    CREATE INDEX idx_session_agents_session_id ON session_agents(session_id);
    CREATE INDEX idx_performance_records_agent_id ON performance_records(agent_id);
    CREATE INDEX idx_improvement_records_agent_id ON improvement_records(agent_id);
    CREATE INDEX idx_execution_history_session_id ON execution_history(session_id);
    CREATE INDEX idx_execution_history_type ON execution_history(type);
    CREATE INDEX idx_token_usage_provider_id ON token_usage(provider_id);
    CREATE INDEX idx_token_usage_session_id ON token_usage(session_id);
    CREATE INDEX idx_permission_audit_agent_id ON permission_audit(agent_id);
    CREATE INDEX idx_prompt_history_session_id ON prompt_history(session_id);
  `);
}
